# Generated by Django 2.2 on 2020-08-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='primaryform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('type_of_lease', models.CharField(max_length=20)),
                ('rent', models.IntegerField(default=0)),
                ('nego1', models.BooleanField(default=False)),
                ('deposit', models.IntegerField(default=0)),
                ('nego2', models.BooleanField(default=False)),
                ('type_of_students', models.CharField(max_length=20)),
                ('restrictions', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='subform_restrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Drinking', models.BooleanField(default=False)),
                ('Smoking', models.BooleanField(default=False)),
                ('Pets', models.BooleanField(default=False)),
                ('Music', models.BooleanField(default=False)),
                ('Guests', models.BooleanField(default=False)),
                ('main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.primaryform')),
            ],
        ),
        migrations.CreateModel(
            name='subform_curfew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curfew_time', models.TimeField()),
                ('no_of_students', models.IntegerField(default=1)),
                ('student_gender', models.CharField(max_length=10)),
                ('main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.primaryform')),
            ],
        ),
        migrations.CreateModel(
            name='subform_amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDining', models.BooleanField(default=False)),
                ('isFurnished', models.BooleanField(default=False)),
                ('noparking', models.IntegerField(default=0)),
                ('no1cupboards', models.IntegerField()),
                ('iswater_puri', models.BooleanField(default=False)),
                ('isAC', models.BooleanField(default=False)),
                ('noBeds', models.IntegerField()),
                ('isWashing_machine', models.BooleanField(default=False)),
                ('isTV', models.BooleanField(default=False)),
                ('isgeyser', models.BooleanField(default=False)),
                ('isPower', models.BooleanField(default=False)),
                ('isPower_bckup', models.BooleanField(default=False)),
                ('iskitchen', models.BooleanField(default=False)),
                ('ismicrowave', models.BooleanField(default=False)),
                ('main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.primaryform')),
            ],
        ),
    ]
